[build]
  functions = "functions"
  publish = "."

[[redirects]]
  from = "/track"
  to = "/.netlify/functions/track"
  status = 200

[[redirects]]
  from = "/data"
  to = "/.netlify/functions/data"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["node-fetch"]
  node_version = "18"